### ISSUE TITLE
Wrong indentation

### ISSUE THREAD

**Issue by gianlucagiacometti** [canonical-web-and-design/netplan.io#163]
In the "Netplan configuration examples" page, "via" and "table" indentations are wrong. They should be aligned with the first letter of "to" or "from"

**Comment by mclemenceau** [comment]
@slyon , Can you check the status on this  one?

**Comment by slyon** [comment]
Yes, indeed. Fixed in: https://github.com/canonical-web-and-design/netplan.io/pull/172
