### ISSUE TITLE
"Chat with netplan" links to freenode

### ISSUE THREAD

**Issue by dbungert** [canonical-web-and-design/netplan.io#173]
## Summary

"Chat with netplan" links to freenode

## Process

https://netplan.io/
Scroll to bottom of page and look at the "Need help" section

## Current and expected result

current: freenode link
expected: liberachat link

## Screenshot

![image](https://user-images.githubusercontent.com/235157/122435689-7199b280-cf55-11eb-9c5d-c4da8dfc5e16.png)

**Comment by fitojb** [comment]
Fixed in #174
