### ISSUE TITLE
`gateway4` is deprecated, but still in the reference without being marked as deprecated

### ISSUE THREAD

**Issue by teward** [canonical-web-and-design/netplan.io#221]
## Summary

Title says it all.  As of netplan in Ubuntu 22.04 (in devel), the `gateway4` and `gateway6` objects are marked as deprecated now.  SO, the reference doesn't reflect this.

https://netplan.io/reference/

## Process

N/A

## Current and expected result

Reference would mention the deprecation and link to explanations in Examples on how to set default routes instead.

## Screenshot

N/A

**Comment by sowasred2012** [comment]
@cpaelzer could you help us with this one?

**Comment by anthonydillon** [comment]
The documentation now states:
```
Deprecated, see Default routes.
```
